default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sample_app_development
  username: root
  host: localhost

test:
  <<: *default
  database: sample_app_test
  username: root
  host: localhost

production:
  primary:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] %>
    username: <%= ENV['DATABASE_USER'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV['DATABASE_HOST'] %>
    port: 3306
  cable:
    <<: *default
  queue:
    <<: *default
  cache:
    <<: *default
