name: Deploy

on:
  push:
    branches:
      - main

env:
  EC2_USER: ubuntu
  DEPLOY_PATH: /home/ubuntu/rails_tutorial

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@${{ secrets.EC2_HOST }} << EOF
            cd $DEPLOY_PATH
            git pull origin main
            bundle install
            yarn install --check-files
            RAILS_ENV=staging bundle exec rake db:migrate
            RAILS_ENV=staging bundle exec rails assets:precompile
            sudo systemctl restart personal-server.service
          EOF
